---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/quarkus-version: "3.15.2"
    app.quarkus.io/vcs-uri: "https://github.com/trustification/trustify-operator.git"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
  labels:
    app.kubernetes.io/name: "trustify-operator"
    app.kubernetes.io/managed-by: "quarkus"
  name: "trustify-operator"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "trustify-operator"
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: "3.15.2"
        app.quarkus.io/vcs-uri: "https://github.com/trustification/trustify-operator.git"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/q/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
      labels:
        app.kubernetes.io/managed-by: "quarkus"
        app.kubernetes.io/name: "trustify-operator"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "RELATED_IMAGE_KEYCLOAK"
          value: "ghcr.io/trustification/trustify-keycloak:latest"
        - name: "RELATED_IMAGE_SERVER"
          value: "ghcr.io/trustification/trustd:latest"
        - name: "RELATED_IMAGE_UI"
          value: "ghcr.io/trustification/trustify-ui:latest"
        - name: "RELATED_IMAGE_DB"
          value: "quay.io/sclorg/postgresql-16-c9s:latest"
        - name: "QUARKUS_OPERATOR_SDK_CONTROLLERS_TRUSTIFY_NAMESPACES"
          value: {{ .Values.watchNamespaces }}
        image: "ghcr.io/trustification/trustify-operator:{{ include "app.tag" . }}"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: "trustify-operator"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/started"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: "trustify-operator"
