trustify:
  default-pvc-size: 10G
  default-requested-cpu: 50m
  default-requested-memory: 64Mi
  default-limit-cpu: 1
  default-limit-memory: 512Mi
"%dev":
  trustify:
    default-pvc-size: 1G
"%test":
  trustify:
    default-pvc-size: 1G
# Operator config
related:
  image:
    ui: ${RELATED_IMAGE_UI:ghcr.io/trustification/trustify-ui:0.2.z}
    server: ${RELATED_IMAGE_SERVER:ghcr.io/trustification/trustd:0.2.z}
    db: ${RELATED_IMAGE_DB:quay.io/sclorg/postgresql-15-c9s:latest}
    keycloak: ${RELATED_IMAGE_KEYCLOAK:ghcr.io/trustification/trustify-keycloak:0.2.z}
    pull-policy: Always
# Quarkus config
quarkus:
  native:
    resources:
      includes: realm.json
  qute:
    suffixes: yaml
  container-image:
    registry: ghcr.io
    tag: v${quarkus.application.version}
  # Increase test hang time since the operator takes time to initiate all deployments
  test:
    hang-detection-timeout: 30M
  operator-sdk:
    crd:
      # set to true to automatically apply CRDs to the cluster when they get regenerated
      apply: true
    namespaces: JOSDK_WATCH_CURRENT
    generate-with-watched-namespaces: JOSDK_WATCH_CURRENT
    helm:
      enabled: true
  # https://quarkus.io/guides/deploying-to-kubernetes#environment-variables-from-keyvalue-pairs
  kubernetes:
    idempotent: "true"
    prometheus:
      generate-service-monitor: "false"
    env:
      vars:
        related-image-ui: ${related.image.ui}
        related-image-server: ${related.image.server}
        related-image-db: ${related.image.db}
        related-image-keycloak: ${related.image.keycloak}
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m
    rbac:
      roles:
        trustify:
          policy-rules:
            - api-groups:
              resources: '*'
              verbs: '*'
            - api-groups: security.openshift.io
              resources: securitycontextconstraints
              verbs: use
              resource-names: anyuid
