package org.trustify.operator.services;

import org.trustify.operator.cdrs.v2alpha1.Trustify;

import java.util.Optional;

public interface Cluster {
    Optional<String> getClusterHostname();
    Optional<String> getAutoGeneratedIngressHost(Trustify cr);
}
