package org.trustify.operator.services;

import io.fabric8.kubernetes.client.KubernetesClient;
import org.trustify.operator.cdrs.v2alpha1.Trustify;

import java.util.Optional;

public class VanillaCluster implements Cluster {

    private final KubernetesClient k8sClient;

    public VanillaCluster(KubernetesClient k8sClient) {
        this.k8sClient = k8sClient;
    }

    @Override
    public Optional<String> getClusterHostname() {
        return Optional.empty();
    }

    @Override
    public Optional<String> getAutoGeneratedIngressHost(Trustify cr) {
        return Optional.empty();
    }

}
