name: Install Trustify operator
description: |
  Install Trustify Operator.
inputs:
  operator-bundle-image:
    description: "image url for operator bundle container image"
    required: false
    default: "ghcr.io/trustification/trustify-operator-bundle:latest"
  server-image:
    description: "image url for the server"
    required: false
    default: "ghcr.io/trustification/trustd:latest"
  image-pull-policy:
    description: "Image Pull Policy"
    required: false
    default: "Always"
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        if command -v kubectl >/dev/null 2>&1; then
          echo "kubectl is already installed...yay"
          exit 0
        fi
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - name: Install operator-sdk
      shell: bash
      run: |
        if command -v operator-sdk >/dev/null 2>&1; then
          echo "operator-sdk is already installed...yay"
          exit 0
        fi
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.35.0/operator-sdk_linux_amd64
        sudo install -o root -g root -m 0755 operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
    - name: Install Trustify
      run: |
        export OPERATOR_BUNDLE_IMAGE="${{ inputs.operator-bundle-image }}"
        export SERVER_IMAGE="${{ inputs.server-image }}"        
        export IMAGE_PULL_POLICY="${{ inputs.image-pull-policy }}"
        make install-trustify
      working-directory: ${{ github.action_path }}/../../..
      shell: bash