name: Install Trustify operator
description: |
  Install Trustify Operator.
inputs:
  operator-bundle-image:
    description: "image url for operator bundle container image"
    required: false
    default: ""
  namespace:
    description: "the namespace where Trustify should be installed"
    required: false
    default: ""
  trustify-cr:
    description: "JSON encoded Trustify Custom Resource (CR) string"
    required: false
    default: ""
  app-name:
    description: "Name of the Trustify instance (should match CR metadata if passed)"
    required: false
    default: "myapp"
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        if command -v kubectl >/dev/null 2>&1; then
          echo "kubectl is already installed...yay"
          exit 0
        fi
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - name: Install operator-sdk
      shell: bash
      run: |
        if command -v operator-sdk >/dev/null 2>&1; then
          echo "operator-sdk is already installed...yay"
          exit 0
        fi
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.35.0/operator-sdk_linux_amd64
        sudo install -o root -g root -m 0755 operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
    - name: Install Trustify
      env:
        OPERATOR_BUNDLE_IMAGE: ${{ inputs.operator-bundle-image }}
        NAMESPACE: ${{ inputs.namespace }}
        APP_NAME: ${{ inputs.app-name }}
        TRUSTIFY_CR: ${{ inputs.trustify-cr }}
      run: |
        make install-trustify
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
