name: Backport
on:
  pull_request_target:
    types: [ closed ]
  issue_comment:
    types: [ created ]
permissions:
  contents: write
  pull-requests: write
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 97796249 &&
        startsWith(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          merge_commits: skip
