name: CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: [ v1.22.17, v1.23.14, v1.24.8, v1.25.3, v1.26.3, v1.27.5, v1.28.1 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Setup Minikube-Kubernetes
        # check version in https://github.com/manusa/actions-setup-minikube/releases
        uses: manusa/actions-setup-minikube@v2.10.0
        with:
          # check version in https://github.com/kubernetes/minikube/releases
          minikube version: 'v1.32.0'
          start args: '--addons=ingress'
          kubernetes version: ${{ matrix.kubernetes_version }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: 'docker'
      - name: Test
        run: |
          mvn verify
